FROM armv7/armhf-ubuntu
MAINTAINER Paul Hoang 2016-12-12
RUN ["mkdir", "-p", "/home/javaapp"]
COPY ./build/libs/sharesGenerator.jar /home/javaapp/sharesGenerator.jar
WORKDIR /home/javaapp
EXPOSE 5551
ENTRYPOINT ["java", "-jar", "sharesGenerator.jar"]
CMD ["uk"]