FROM armv7/armhf-ubuntu
MAINTAINER Paul Hoang 2016-12-12
RUN ["apt-get", "install", "openjdk-8-jre", "--no-install-recommends", "-y"]
RUN ["mkdir", "-p", "/home/javaapp"]
COPY ./build/libs/sharesGenerator.jar /home/javaapp/sharesGenerator.jar
WORKDIR /home/javaapp
EXPOSE 5551
EXPOSE 5552
EXPOSE 5553
EXPOSE 5554
ENTRYPOINT ["java", "-jar", "sharesGenerator.jar"]
CMD ["uk"]
#CMD ["/bin/bash"]
